[package]
name = "constructor"
version = "0.1.0"
authors = ["neptunepink <purpleposeidon@gmail.com>"]
license = "MIT/Apache-2.0"
description = "static initializers"
repository = "https://github.com/purpleposeidon/constructor"

[dev-dependencies]
zalgo = "0.1.*"
